# $FreeBSD$

compute_engine_instance:
  # Image list available via
  # gcloud compute images list --project freebsd-org-cloud-dev --no-standard-images
  platform: freebsd
  image_project: freebsd-org-cloud-dev
  image: freebsd-13-0-release-amd64

task:
  name: OCI
  environment:
    PAR_URL: https://example.com
  install_script:
  - pkg install -y curl
  script:
  - hostname > local-file
  - curl -X PUT --data-binary '@local-file' ${PAR_URL}/remote-file
