# $FreeBSD$

compute_engine_instance:
  # Image list available via
  # gcloud compute images list --project freebsd-org-cloud-dev --no-standard-images
  platform: freebsd
  image_project: freebsd-org-cloud-dev
  image: freebsd-13-0-release-amd64

task:
  name: OCI
  environment:
    TENANCY: ENCRYPTED[7d2b99264390b5b442adc085ffb7197b706fc0d35442439f0da0d074a88cddb21d7dd7fe5e701dabf6c738faf56f5dad]
  install_script:
  # - pkg install -y py38-oci
  oci_script:
  - fetch https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
  - sh install.sh --accept-all-defaults
  script:
  - oci os bucket list --compartment-id ${TENANCY}
