# $FreeBSD$

compute_engine_instance:
  # Image list available via
  # gcloud compute images list --project freebsd-org-cloud-dev --no-standard-images
  platform: freebsd
  image_project: freebsd-org-cloud-dev
  image: freebsd-13-0-release-amd64

task:
  name: OCI
  environment:
    TENANCY: ENCRYPTED[foo]
  install_script:
  - pkg install -y py38-oci
  script:
  - oci os bucket list --compartment-id ${TENANCY}
